# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbab3e5159250903e75467ee0aaae3c8fa1ef974d34c5553b3051e6054e28d4692ff7e35aee194bcc52df33f81cb851abefb8bf9ae995c10d0a8dcf30ac845e

test:
  secret_key_base: 0fadb29fad73d76b3b640b0c0ede6a0707e47c6994fc066c16eaf82bad2689149b147c950018110f6cb5caa26477e8ce958c5040ba2c8ed3f91ebe541a2652d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
